# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moderate.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emoderate.proto\"7\n\x11\x46unctionParameter\x12\x10\n\x08strparam\x18\x01 \x01(\t\x12\x10\n\x08numparam\x18\x02 \x01(\x05\"!\n\x11\x46unctionReturnVal\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x32@\n\x04\x45ric\x12\x38\n\x0c\x65ricFunction\x12\x12.FunctionParameter\x1a\x12.FunctionReturnVal\"\x00\x32\x7f\n\x0bMyFunctions\x12\x37\n\x0bmyfunction1\x12\x12.FunctionParameter\x1a\x12.FunctionReturnVal\"\x00\x12\x37\n\x0bmyfunction2\x12\x12.FunctionParameter\x1a\x12.FunctionReturnVal\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moderate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FUNCTIONPARAMETER']._serialized_start=18
  _globals['_FUNCTIONPARAMETER']._serialized_end=73
  _globals['_FUNCTIONRETURNVAL']._serialized_start=75
  _globals['_FUNCTIONRETURNVAL']._serialized_end=108
  _globals['_ERIC']._serialized_start=110
  _globals['_ERIC']._serialized_end=174
  _globals['_MYFUNCTIONS']._serialized_start=176
  _globals['_MYFUNCTIONS']._serialized_end=303
# @@protoc_insertion_point(module_scope)
